### ISSUE TITLE
Design update task tracker

### ISSUE THREAD

**Issue by imrehg** [imrehg/cdei-development#54]
Things need to happen to design before handover, add new items as they come:

* [x] Header logo replacement with CDEI one
* [ ] Licenses update #6
* [x] Author update in files
* [x] Updated favicon #5 
* [x] New social preview image
* [x] Loader colour
* [x] Fonts review
* [x] Dealing with "Theme by Rocketseat" item in the bottom (repurpose it for copyright?)
* [x] Plot theming #24
* [ ] Styling of 404 page 
* [x] Small screen plots #91 
* [x] Soften `code snippet` styling (it's too dark)
* [x] Unresponsive collapsibles on page load #92

**Comment by imrehg** [comment]
Done what we wanted so far.
